# Blazer configuration
# see https://github.com/ankane/blazer for more info

data_sources:
  main:
    production:
      url: <%= ENV["BLAZER_DATABASE_URL"] || ENV["DATABASE_URL"] %>

audit: true

user_class: User
user_method: current_blazer_user
user_name: name_for_admin
before_action_method: require_admin
